# General settings
title:
  en: '**GitHub Pages** boilerplate' # feel free to use Markdown
  cs: 'Boilerplate pro **GitHub Pages**'
description: # feel free to use Markdown
  en: >- # this ignores newlines until the next definition
    Jekyll boilerplate for [GitHub Pages](https://pages.github.com) (no plugins) does the every-time-new-static-site
    groundwork for you. Featuring multilanguage and shared codebase for multiple connected 
    sites.
  cs: >-
    Základy pro spuštění statické stránky generované pomocí Jekyllu a hostované
    na [GitHub Pages](https://pages.github.com). Poradí si i s multijazyčností a sdílením codebase pro víc stránek.
language: # ISO 639-1 language code
  - en # first language in the list is default
  - cs
environment: production # if not production, all URLs will be disallowed for crawling and will contain noindex meta tag


# Crawling & indexing
robots: # optional list of custom URLs to disallow crawling
  - 'noindex.pdf'

# Page titles
page_title:
  append: true # site title will be appended after page title (if set)

# Google Tag Manager
gtm_container_id: GTM-O3A98T7

defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false
  -
    scope:
      path:            "_posts/**"
    values:
      sitemap:         false
  -
    scope:
      path:            "_staff_members/**"
    values:
      sitemap:         false
  -
    scope:
      path:            "index.md"
    values:
      private:         true



# HTML compression using jekyll-compress-html layout settings (see jch.penibelst.de)
compress_html:
  clippings: all
  ignore:
    envs:
      - production # remove this line to enable HTML compression
      - development

# Plugins
plugins: # only GitHub Pages supported plugins may be used: pages.github.com/versions
  - jekyll-sitemap
